name: github action workflow
on:
  push:
    branches:
      - main
      - feature/u*
  workflow_dispatch:
    inputs:
      image_tag:
        description: "docker image tag"
        required: true
        default: latest


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v4

      - name: build Docker image
        run : docker build -t my-nginx:${{ inputs.image_tag }} .

      - name: show the docker selected tag
        run : echo "build docker image for ${{ inputs.image_tag }}" 
