name: github actions workflows
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the source code
        uses: actions/checkout@v4

      - name: print hello message
        run: echo "hello"
