name: github action workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v4

      - name: build Docker image
        run : docker build -t my-nginx:v1 .
